/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_brown_cs_systems_clockcycles_CPUCycles */

#ifndef _Included_edu_brown_cs_systems_clockcycles_CPUCycles
#define _Included_edu_brown_cs_systems_clockcycles_CPUCycles
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_brown_cs_systems_clockcycles_CPUCycles
 * Method:    getNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_brown_cs_systems_clockcycles_CPUCycles_getNative(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
